workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      vars:
        FIREBASE_APP_ID: "1:947149653644:ios:f65e080c90dfff03f99da9"
        GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;

      - name: Flutter build ipa
        script: |
          flutter build ipa --release --no-codesign
          mkdir -p build/ios/ipa
          cp -r build/ios/iphoneos/Runner.app build/ios/ipa/ || echo "No IPA files found"

      - name: Distribute to Firebase App Distribution
        script: |
          # Check if Firebase CLI is already installed
          if ! command -v firebase &> /dev/null; then
            echo "Installing Firebase CLI..."
            npm install -g firebase-tools
          else
            echo "Firebase CLI is already installed."
          fi

          # Authenticate with Firebase using the service account JSON
          echo "Authenticating with Firebase..."
          echo "$GOOGLE_APPLICATION_CREDENTIALS" > /tmp/service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS="/tmp/service-account.json"

          # Verify authentication
          echo "Verifying Firebase authentication..."
          firebase login --non-interactive --token "$(cat /tmp/service-account.json | jq -r '.private_key')"

          # Distribute the app bundle
          echo "Distributing app bundle to Firebase App Distribution..."
          firebase appdistribution:distribute build/ios/ipa/Runner.app \
            --app $FIREBASE_APP_ID \
            --groups "testers" \
            --release-notes "Build ${CM_BUILD_NUMBER} - Unsigned iOS App"

    artifacts:
      - build/ios/ipa/Runner.app

    publishing:
      email:
        recipients:
          - laleye.solomon@yahoo.com
          - laleyesolomon2@gmail.com
          - laleyesolomon3@gmail.com
          - nihal@nevercode.io
        notify:
          success: true
          failure: false
