workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - testers

    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..

      - name: Authenticate with Firebase using Token
        script: |
          echo "🔄 Verifying Firebase authentication..."
          echo "FIREBASE_TOKEN: $FIREBASE_TOKEN"
          echo "GOOGLE_APPLICATION_CREDENTIALS_JSON: $GOOGLE_APPLICATION_CREDENTIALS_JSON"
          echo "✅ Firebase authentication successful"

      - name: Build iOS App
        script: |
          flutter clean
          flutter build ios
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            -allowProvisioningUpdates \
            build

      - name: Create IPA Package
        script: |
          IPA_DIR="build/ios/ipa"
          APP_PATH="build/ios/iphoneos/Runner.app"
          IPA_PATH="$IPA_DIR/app.ipa"

          mkdir -p "$IPA_DIR"
          rm -rf Payload
          mkdir Payload
          cp -R "$APP_PATH" Payload/
          zip -r "$IPA_PATH" Payload

          if [ -f "$IPA_PATH" ]; then
            echo "✅ IPA successfully created at $IPA_PATH"
          else
            echo "❌ Failed to create IPA"
            exit 1
          fi

      - name: Distribute to Firebase
        script: |
          firebase appdistribution:distribute build/ios/ipa/app.ipa \
            --app "$FIREBASE_APP_ID" \
            --groups "testers" \
            --release-notes "Build $CM_BUILD_NUMBER - Unsigned IPA" \
            --token "$FIREBASE_TOKEN"

    artifacts:
      - build/ios/ipa/app.ipa

    publishing:
      email:
        recipients:
          - laleye.solomon@yahoo.com
          - laleyesolomon2@gmail.com
        notify:
          success: true
          failure: true
