workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - code-signing
      ios_signing:
        provisioning_profiles:
          - CodeMagicFlutterApp
        certificates:
          - CodemagicFlutterApp
    scripts:
      - name: Debug Certificates
        script: |
          echo "Checking certificate files..."
          ls -al /Users/builder/Library/MobileDevice/Provisioning\ Profiles/
          ls -al /Users/builder/

      # - name: Fetch Provisioning Profile
      #   script: |
      #     echo "Fetching provisioning profile from Codemagic..."
      #     app-store-connect fetch-signing-files "com.codemagicFlutterApp.test" --type IOS_ADHOC
      #     ls -al /Users/builder/Library/MobileDevice/Provisioning\ Profiles/

      - name: Use Profiles
        script: xcode-project use-profiles

      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Authenticate with Firebase using Token
        script: |
          echo "🔄 Verifying Firebase authentication..."
          echo "FIREBASE_TOKEN: $FIREBASE_TOKEN"
          echo "GOOGLE_APPLICATION_CREDENTIALS_JSON: $GOOGLE_APPLICATION_CREDENTIALS_JSON"
          echo "✅ Firebase authentication successful"

      - name: Build IPA with automatic versioning
        script: |
          flutter build ipa --export-options-plist=/Users/builder/export_options.plist

      - name: Distribute to Firebase
        script: |
          firebase appdistribution:distribute build/ios/ipa/Runner.ipa \
            --app "$FIREBASE_APP_ID" \
            --groups "testers" \
            --release-notes "Build $CM_BUILD_NUMBER - Signed IPA" \
            --token "$FIREBASE_TOKEN"

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/Runner.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app

    publishing:
      email:
        recipients:
          - laleye.solomon@yahoo.com
          - laleyesolomon2@gmail.com
        notify:
          success: true
          failure: false
