workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      vars:
        FIREBASE_APP_ID: "1:947149653644:ios:f65e080c90dfff03f99da9"
        FIREBASE_TOKEN: $FIREBASE_TOKEN
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Flutter packages
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build IPA (Unsigned)
        script: |
          flutter build ipa --release --no-codesign

          if [ ! -f "build/ios/ipa/Runner.ipa" ]; then
            echo "Error: IPA file not found at build/ios/ipa/Runner.ipa"
            exit 1
          else
            echo "✅ IPA generated at build/ios/ipa/Runner.ipa"
          fi

      - name: Distribute to Firebase
        script: |
          echo "FIREBASE_APP_ID: $FIREBASE_APP_ID"

          echo "FIREBASE_TOKEN: ${FIREBASE_TOKEN:0:10}..."

          if [ ! -f "build/ios/ipa/Runner.ipa" ]; then
            echo "Error: IPA file not found at build/ios/ipa/Runner.ipa"
            exit 1
          else
            echo "IPA file found at build/ios/ipa/Runner.ipa"
          fi

          firebase appdistribution:distribute build/ios/ipa/Runner.ipa \
            --app "$FIREBASE_APP_ID" \
            --token "$FIREBASE_TOKEN" \
            --groups "testers" \
            --release-notes "Build $CM_BUILD_NUMBER - Unsigned IPA"

    artifacts:
      - build/ios/ipa/Runner.ipa

    publishing:
      email:
        recipients:
          - laleye.solomon@yahoo.com
          - laleyesolomon2@gmail.com
        notify:
          success: true
          failure: true
