workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      vars:
        FIREBASE_APP_ID: "1:947149653644:ios:f65e080c90dfff03f99da9"
        GOOGLE_APPLICATION_CREDENTIALS_BASE64: $GOOGLE_APPLICATION_CREDENTIALS_BASE64
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Flutter packages
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build IPA
        script: |
          flutter build ipa --release --no-codesign
          echo "✅ IPA generated at build/ios/ipa/Runner.ipa"

      - name: Debug - Check GOOGLE_APPLICATION_CREDENTIALS_BASE64
        script: |
          if [ -z "$GOOGLE_APPLICATION_CREDENTIALS_BASE64" ]; then
            echo "Error: GOOGLE_APPLICATION_CREDENTIALS_BASE64 is empty or not set"
            exit 1
          else
            echo "GOOGLE_APPLICATION_CREDENTIALS_BASE64 is set"
            echo "Length of GOOGLE_APPLICATION_CREDENTIALS_BASE64: ${#GOOGLE_APPLICATION_CREDENTIALS_BASE64}"
            echo "First 100 characters of GOOGLE_APPLICATION_CREDENTIALS_BASE64: ${GOOGLE_APPLICATION_CREDENTIALS_BASE64:0:100}"
          fi

          CLEAN_BASE64=$(echo "$GOOGLE_APPLICATION_CREDENTIALS_BASE64" | tr -d '\n')
          echo "$CLEAN_BASE64" | base64 -d > /tmp/service-account.json

          if ! jq empty /tmp/service-account.json; then
            echo "Error: Decoded service account JSON is invalid"
            exit 1
          else
            echo "Service account JSON is valid"
          fi

      - name: Distribute to Firebase
        script: |
          export GOOGLE_APPLICATION_CREDENTIALS="/tmp/service-account.json"

          firebase appdistribution:distribute build/ios/ipa/Runner.ipa \
            --app "$FIREBASE_APP_ID" \
            --groups "testers" \
            --release-notes "Build $CM_BUILD_NUMBER - Unsigned IPA"

    artifacts:
      - build/ios/ipa/Runner.ipa

    publishing:
      email:
        recipients:
          - laleye.solomon@yahoo.com
          - laleyesolomon2@gmail.com
        notify:
          success: true
          failure: true
