workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..
      - name: Build IPA
        # script: flutter build ipa --release --export-options-plist=ios/ExportOptions.plist
        script: |
          flutter build ipa --release --no-codesign
          mkdir -p build/ios/ipa
          mv build/ios/iphoneos/*.ipa build/ios/ipa/

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      firebase:
        credentials: $GOOGLE_APPLICATION_CREDENTIALS
        app_id: $FIREBASE_APP_ID
        groups: testers
        release_notes: "Build ${CM_BUILD_NUMBER} - iOS App"
      email:
        recipients:
          - laleye.solomon@yahoo.com
          - laleyesolomon2@gmail.com
          - laleyesolomon3@gmail.com
          - nihal@nevercode.io
        notify:
          success: true
