workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..
      - name: Build IPA
        script: flutter build ipa --release --export-options-plist=ios/ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      firebase:
        firebase_token: 1//03wTSdSULv0iHCgYIARAAGAMSNwF-L9Ir-dvb54xNPsrtZ8-0Vgf23ClvJHO_G4hTFEe_jJP0Ekj6cNTR0WQ22mfKSoHZyy741cU
        app_id: 1:947149653644:ios:f65e080c90dfff03f99da9
        groups: testers
        release_notes: "Build ${CM_BUILD_NUMBER} - Default Flutter App"
      email:
        recipients:
          - laleye.solomon@yahoo.com
          - laleyesolomon2@gmail.com
          - nihal@nevercode.io
        notify:
          success: true
