workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        FIREBASE_APP_ID: "1:947149653644:ios:f65e080c90dfff03f99da9"
        GOOGLE_APPLICATION_CREDENTIALS_BASE64: Encrypted_Service_Account_JSON

    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..

      - name: Write Service Account JSON to a File
        script: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" | base64 --decode > /tmp/service_account.json
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/service_account.json
          echo "Service account JSON file created at /tmp/service_account.json"

      - name: Build iOS App (Unsigned)
        script: |
          flutter build ios --no-codesign

      - name: Package .app into .ipa (Manually)
        script: |
          mkdir -p build/ios/ipa/Payload
          cp -r build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -r app.ipa Payload
          rm -rf Payload
          cd ../../../..

          # Debug: Check if IPA was created
          if [ -f "build/ios/ipa/app.ipa" ]; then
            echo "✅ IPA successfully created at build/ios/ipa/app.ipa"
          else
            echo "❌ Failed to create IPA"
            exit 1
          fi

      - name: Distribute to Firebase
        script: |
          if [ ! -f "build/ios/ipa/app.ipa" ]; then
            echo "❌ Error: IPA file not found!"
            exit 1
          fi

          firebase appdistribution:distribute build/ios/ipa/app.ipa \
            --app "$FIREBASE_APP_ID" \
            --service-account "/tmp/service_account.json" \
            --groups "testers" \
            --release-notes "Build $CM_BUILD_NUMBER - Unsigned IPA"

    artifacts:
      - build/ios/ipa/app.ipa

    publishing:
      email:
        recipients:
          - laleye.solomon@yahoo.com
          - laleyesolomon2@gmail.com
        notify:
          success: true
          failure: true
