workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        FIREBASE_APP_ID: "1:947149653644:ios:f65e080c90dfff03f99da9"
        FIREBASE_TOKEN: Encrypted_Firebase_Token # Add in Codemagic UI

    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..

      - name: Authenticate with Firebase using Token
        script: |
          echo "🔄 Verifying Firebase authentication..."
          firebase projects:list --token "$FIREBASE_TOKEN"

          if [ $? -ne 0 ]; then
            echo "❌ Firebase authentication failed. Ensure the token is correct."
            exit 1
          fi

          echo "✅ Firebase authentication successful"

      - name: Build iOS App (Unsigned)
        script: |
          flutter clean
          flutter build ios --no-codesign

      - name: Validate Build Output
        script: |
          if [ ! -d "build/ios/iphoneos/Runner.app" ]; then
            echo "❌ Error: Runner.app not found! Build failed."
            exit 1
          else
            echo "✅ Runner.app found! Proceeding with IPA creation."
          fi

      - name: Create IPA Package
        script: |
          IPA_DIR="build/ios/ipa"
          APP_PATH="build/ios/iphoneos/Runner.app"
          IPA_PATH="$IPA_DIR/app.ipa"

          mkdir -p "$IPA_DIR"
          rm -rf Payload
          mkdir Payload
          cp -R "$APP_PATH" Payload/
          zip -r "$IPA_PATH" Payload

          if [ -f "$IPA_PATH" ]; then
            echo "✅ IPA successfully created at $IPA_PATH"
          else
            echo "❌ Failed to create IPA"
            exit 1
          fi

      - name: Distribute to Firebase
        script: |
          if [ ! -f "build/ios/ipa/app.ipa" ]; then
            echo "❌ Error: IPA file not found!"
            exit 1
          fi

          firebase appdistribution:distribute build/ios/ipa/app.ipa \
            --app "$FIREBASE_APP_ID" \
            --groups "testers" \
            --release-notes "Build $CM_BUILD_NUMBER - Unsigned IPA" \
            --token "$FIREBASE_TOKEN"

    artifacts:
      - build/ios/ipa/app.ipa

    publishing:
      email:
        recipients:
          - laleye.solomon@yahoo.com
          - laleyesolomon2@gmail.com
        notify:
          success: true
          failure: true
