workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      vars:
        FIREBASE_APP_ID: "1:947149653644:ios:f65e080c90dfff03f99da9"
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - firebase
      scripts:
        - |
          echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > /tmp/service_account.json
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/service_account.json

    scripts:
      - name: Install Flutter packages
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build IPA
        script: |
          flutter build ipa --no-codesign

      - name: Distribute to Firebase
        script: |
          firebase appdistribution:distribute build/ios/ipa/*.ipa \
            --app "$FIREBASE_APP_ID" \
            --service-account "/tmp/service_account.json" \
            --groups "testers" \
            --release-notes "Build $CM_BUILD_NUMBER - Unsigned IPA"

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - laleye.solomon@yahoo.com
          - laleyesolomon2@gmail.com
        notify:
          success: true
          failure: true
