workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      vars:
        # FIREBASE_APP_ID: "1:947149653644:ios:f65e080c90dfff03f99da9"
        FIREBASE_TOKEN: $FIREBASE_TOKEN
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;

      - name: Flutter analyze
        script: |
          flutter analyze

      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true

      - name: Flutter build ipa
        script: |
          flutter build ipa --release --no-codesign
          mkdir -p build/ios/ipa
          mv build/ios/iphoneos/*.ipa build/ios/ipa/ || echo "No IPA files found"

      - name: Distribute to Firebase App Distribution
        script: |
          # Install Firebase CLI
          npm install -g firebase-tools

          # Authenticate with Firebase using the token
          firebase login:ci --token $FIREBASE_TOKEN

          # Distribute the IPA
          firebase appdistribution:distribute build/ios/ipa/*.ipa \
            --app $FIREBASE_APP_ID \
            --groups "testers" \
            --release-notes "Build ${CM_BUILD_NUMBER} - Unsigned iOS App"

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - laleye.solomon@yahoo.com
          - laleyesolomon2@gmail.com
          - laleyesolomon3@gmail.com
          - nihal@nevercode.io
        notify:
          success: true
          failure: false
