workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - code-signing
    integrations:
      app_store_connect: solomonappstorekey

  # ios_signing: |
  #     distribution_type: app_store
  #     bundle_identifier: com.codemagicFlutterApp.test
    scripts:
      - name: Set up code signing settings on Xcode project
        script: keychain initialize
    scripts:
      - name: Add Certificates
        script: add-certificates
    scripts:
      - name: Use profiles
        script: xcode-project use-profiles

      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Authenticate with Firebase using Token
        script: |
          echo "🔄 Verifying Firebase authentication..."
          echo "FIREBASE_TOKEN: $FIREBASE_TOKEN"
          echo "GOOGLE_APPLICATION_CREDENTIALS_JSON: $GOOGLE_APPLICATION_CREDENTIALS_JSON"
          echo "✅ Firebase authentication successful"

      - name: Build IPA with automatic versioning
        script: |
          flutter build ipa --export-options-plist=/Users/builder/export_options.plist

      - name: Distribute to Firebase
        script: |
          firebase appdistribution:distribute build/ios/ipa/Runner.ipa \
            --app "$FIREBASE_APP_ID" \
            --groups "testers" \
            --release-notes "Build $CM_BUILD_NUMBER - Signed IPA" \
            --token "$FIREBASE_TOKEN"

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/Runner.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app

    publishing:
      email:
        recipients:
          - laleye.solomon@yahoo.com
          - laleyesolomon2@gmail.com
        notify:
          success: true
          failure: false
