workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: stable
      xcode: latest
      vars:
        FIREBASE_APP_ID: 1:947149653644:ios:f65e080c90dfff03f99da9
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..

      - name: Build IPA
        script: |
          flutter build ipa --release --no-codesign
          mkdir -p build/ios/ipa
          mv build/ios/iphoneos/*.ipa build/ios/ipa/ || echo "No IPA files found"

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      # Distribute to Firebase App Distribution
      firebase:
        credentials: $GOOGLE_APPLICATION_CREDENTIALS
        app_id: $FIREBASE_APP_ID
        groups: testers
        release_notes: "Build ${CM_BUILD_NUMBER} - Unsigned iOS App"

      # Email notifications
      email:
        recipients:
          - laleye.solomon@yahoo.com
          - laleyesolomon2@gmail.com
          - laleyesolomon3@gmail.com
          - nihal@nevercode.io
        notify:
          success: true
