workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - testers

    scripts:
      - name: Set up keychain and provisioning profile
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "com.example.codemagicFlutterApp" --type IOS_ADHOC
          xcode-project use-profiles

      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..

      - name: Authenticate with Firebase using Token
        script: |
          echo "🔄 Verifying Firebase authentication..."
          echo "FIREBASE_TOKEN: $FIREBASE_TOKEN"
          echo "GOOGLE_APPLICATION_CREDENTIALS_JSON: $GOOGLE_APPLICATION_CREDENTIALS_JSON"
          echo "✅ Firebase authentication successful"

      - name: Build iOS App
        script: |
          flutter clean
          flutter pub get
          flutter build ios --no-codesign
          xcode-project build-ipa

      - name: Distribute to Firebase
        script: |
          firebase appdistribution:distribute build/ios/ipa/Runner.ipa \
            --app "$FIREBASE_APP_ID" \
            --groups "testers" \
            --release-notes "Build $CM_BUILD_NUMBER - Signed IPA" \
            --token "$FIREBASE_TOKEN"

    artifacts:
      - build/ios/ipa/Runner.ipa

    publishing:
      email:
        recipients:
          - laleye.solomon@yahoo.com
          - laleyesolomon2@gmail.com
        notify:
          success: true
          failure: false
